import LocalizedStrings from "react-localization";

const hotelName = "Taj Wellington Mews";

export const strings = new LocalizedStrings({
  en: {
    appTitle: [hotelName],
    bookingIdTextfieldLabel: "Booking ID",
    bookingIdConfirmationButton: "Next",
    confirmYourBookingId: "Enter Your Booking ID",
    textValidatorRequiredErrorMessage: "Please enter your Booking ID.",
    termsAndConditionsPageHeadingText: "Terms & Conditions",
    termsAndConditionsPageCheckboxLabel: "Accept",
    termsAndConditionsPageNextButton: "Next",
    textfieldReset: "",
    termsAndConditionsOne: "Check-In from 2:00 PM.",
    termsAndConditionsTwo: "Check-Out till 12:00 PM.",
    termsAndConditionsThree: "Early check-in and late check-out on request.",
    termsAndConditionsFour:
      "We accept American Express, Diner Club, Master Card, Visa, JCB International.",
    termsAndConditionsFive: "Pets are not allowed.",
    pageNotFound: "Page not found",
    homePageLinkText: "Home",
    showQrCodeToReceptionist:
      "Please show the QR code at reception to check-in!",
    thanksForSubmittingDocument: "Thanks for submitting your document!",
    roomAssignText: "You have been assigned room number: 105",
    errorDialogboxTitle: "Error",
    bookingIdPageErrorDialogboxContentInvalidIdText: "Booking ID is invalid!",
    errorDialogboxContentServerUnavailableText:
      "The server is temporarily unavailable!",
    bookingIdPageErrorDialogboxButtonText: "OK",
    welcomeText: "Welcome ",
    thankYouMessage: "Thanks for choosing " + [hotelName],
    checkoutTimeMessage: "Check-out Date: ",
    checkinTimeMessage: "Check-in Date: ",
    welcomePageNextButton: "Next",
    errorGoToHome: "Go to home",
    homeLink: "Home",
    imageUploadHeader: "Proof of Identity",
    imageUploadInfoTest:
      "Please upload your document to confirm your identify.",
    documentsToUpload: "Documents that you can upload-",
    aadharCard: "Aadhar Card",
    drivingLicense: "Driving License",
    passport: "Passport",
    imageSelectText: "Select Image",
    noImageSelected: "No Image Selected",
    noImageSelectedAlert: "Please select image to upload!",
    imageUploadButton: "Upload",
    imageUploadPageDialogboxTitle: "Success",
    imageUploadPageDialogboxContentSuccessText:
      "Your document has been successfully uploaded!",
    imageUploadPageDialogboxContentErrorText: "Image already exist!",
    imageUploadPageDialogboxButtonText: "OK",
    upgradeTitle: "Upgrade Your Booking",
    masterSuitePrimaryText: "Master Suite",
    masterSuiteSecondaryText: "₹ 5000",
    queenExecutivePrimaryText: "Queen Executive",
    queenExecutiveSecondaryText: "₹ 3000",
    kingExecutivePrimaryText: "King Executive",
    kingExecutiveSecondaryText: "₹ 3500",
    totalAmount: "Amount: ₹ ",
    upgradeFinishButton: "Continue",
    generateQrCode: "Generate QrCode",
    startScan: "Place the code inside the frame.",
    camDenied: "Camera permission denied.",
    unrecognisedQrCode: "Your QR code was not recognised.",
    scanToVerify: "Scan QR code for Customer Verification.",
    scan: "Scan QrCode",
    confirmVerfiy: "Confirm Verification",
    confirmCheckIn: "Check-In Confirmed!",
    roomAssign: "Room Assigned: ",
    roomNumber: "105",
    additionalCost: "Cost for Upgraded Features: ",
    customerIdProof: "'s ID Proof",
    noIdProof: "ID Proof Not Uploaded.",
    rupees: "₹ ",
    noCheckIn: "Check-In not completed."
  }
});
